FROM node:16-stretch

RUN  apt-get update \
     && apt-get install -y wget gnupg ca-certificates \
     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
     && apt-get update \
     && apt-get install -y google-chrome-stable \
     && rm -rf /var/lib/apt/lists/* \

WORKDIR /usr/app
COPY ./ ./
RUN npm install puppeteer --unsafe-perm=true --allow-root
RUN node node_modules/puppeteer/install.js
RUN npm install
